# Generated by Django 3.1.4 on 2020-12-20 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('username', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=18)),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=15)),
                ('std', models.IntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
    ]
