# Generated by Django 3.1.4 on 2020-12-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_tempreader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempReader',
        ),
    ]
