# Generated by Django 3.1.4 on 2020-12-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0006_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='code',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
