# Generated by Django 3.1.4 on 2020-12-20 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=20)),
                ('cover', models.ImageField(upload_to='static/books')),
                ('description', models.CharField(max_length=400)),
                ('topic', models.CharField(default='ALL', max_length=40)),
                ('standard', models.IntegerField(default=6)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=18)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='BookExtra',
            fields=[
                ('book_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('confirmation_id', models.CharField(max_length=8)),
                ('status', models.CharField(default='available', max_length=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.book')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
    ]
