# Generated by Django 3.1.4 on 2020-12-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('coupon', models.CharField(default='000', max_length=12)),
                ('tme', models.DateTimeField()),
            ],
        ),
    ]
