# Generated by Django 3.1.4 on 2020-12-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_festbook_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festbook',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
