# Generated by Django 3.1.4 on 2020-12-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20201225_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festorder',
            name='author',
        ),
        migrations.RemoveField(
            model_name='festorder',
            name='name',
        ),
        migrations.AddField(
            model_name='festorder',
            name='bookid',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='festorder',
            name='coupon',
            field=models.CharField(default='000', max_length=12, null=True),
        ),
    ]
