# Generated by Django 3.1.4 on 2020-12-25 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0007_auto_20201224_0747'),
        ('event', '0005_auto_20201225_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='festorder',
            name='userid',
            field=models.ForeignKey(default='reader2', on_delete=django.db.models.deletion.CASCADE, to='reader.reader'),
            preserve_default=False,
        ),
    ]
