# Generated by Django 3.1.4 on 2020-12-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_festorder_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='festorder',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
