# Generated by Django 3.1.4 on 2020-12-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_festorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festorder',
            name='orderId',
            field=models.CharField(max_length=50),
        ),
    ]
