# Generated by Django 3.1.4 on 2020-12-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20201225_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='festorder',
            name='address',
            field=models.TextField(default='Not provided'),
            preserve_default=False,
        ),
    ]
